### ISSUE TITLE
Use ILoggingBuilder

### ISSUE THREAD

**Issue by SalvadorSarpi** [ilya-chumakov/LoggingAdvanced#3]
Hi, I think it would be nice to use the ILoggingBuilder interface, instead of ILoggerFactory to register the AdvancedConsole logger. This seems to be the preferred way. I can take care of it, then send you a PR?

**Comment by ilya-chumakov** [comment]
Closed because of https://github.com/ilya-chumakov/LoggingAdvanced/releases/tag/v0.4.0
