### ISSUE TITLE
Getting both regular log + your logging

### ISSUE THREAD

**Issue by TXX-JSR** [ilya-chumakov/LoggingAdvanced#7]
Hi, I installed your LoggingAdvanced but now I receive duplicated info from the regular log and the advanced. For exemple:

info: EasyPay.Services.TimedHostedService[0]
      Timed Background Service is working.
[2018.11.02 14:52:08] info: TimedHostedService      Timed Background Service is working.

What must I change to avoid the regular logging ? Thanks.

**Comment by ilya-chumakov** [comment]
Sorry for late reply (I was on a long vacation with no access to the Internet). In .NET Core 2.0, check the `WebHostBuilder.ConfigureLogging` method and make sure there are no `AddConsole` calls registering a regular logger.
